name: Continuous Integration
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: |
          npm install
      - name: setup
        run: |
          npx ts-node ./tools/setup.ts --reset
      - name: build
        run: |
          npx ts-node ./tools/create_web-page-hpp.ts
          ./arduino/arduino-cli --verbose --config-file arduino-cli.yaml compile --fqbn esp8266:esp8266:nodemcuv2:xtal=160,vt=flash,exception=disabled,stacksmash=disabled,ssl=all,mmu=4816,non32xfer=fast,eesz=4M,led=2,ip=hb2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200 digital-clock-esp8266
